<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260620184318 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE account (id UUID NOT NULL, name VARCHAR(120) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE account_membership (id UUID NOT NULL, role VARCHAR(255) NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7A6420219B6B5FBA ON account_membership (account_id)');
        $this->addSql('CREATE INDEX IDX_7A642021A76ED395 ON account_membership (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_membership_account_user ON account_membership (account_id, user_id)');
        $this->addSql('CREATE TABLE broker_connection (id UUID NOT NULL, broker_type VARCHAR(255) NOT NULL, label VARCHAR(120) NOT NULL, encrypted_credentials TEXT NOT NULL, active BOOLEAN NOT NULL, last_sync_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1935D6609B6B5FBA ON broker_connection (account_id)');
        $this->addSql('CREATE TABLE import_batch (id UUID NOT NULL, broker_type VARCHAR(255) NOT NULL, source VARCHAR(255) NOT NULL, file_name VARCHAR(255) DEFAULT NULL, status VARCHAR(255) NOT NULL, rows_imported INT NOT NULL, rows_skipped INT NOT NULL, errors JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, account_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_155EFD1A9B6B5FBA ON import_batch (account_id)');
        $this->addSql('CREATE INDEX idx_import_account ON import_batch (account_id, created_at)');
        $this->addSql('CREATE TABLE instrument (id UUID NOT NULL, symbol VARCHAR(32) NOT NULL, isin VARCHAR(12) DEFAULT NULL, name VARCHAR(160) NOT NULL, type VARCHAR(255) NOT NULL, currency VARCHAR(3) NOT NULL, exchange VARCHAR(32) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_instrument_isin ON instrument (isin)');
        $this->addSql('CREATE TABLE invitation (id UUID NOT NULL, email VARCHAR(180) NOT NULL, role VARCHAR(255) NOT NULL, token VARCHAR(64) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id UUID NOT NULL, invited_by_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F11D61A29B6B5FBA ON invitation (account_id)');
        $this->addSql('CREATE INDEX IDX_F11D61A2A7B4A7E3 ON invitation (invited_by_id)');
        $this->addSql('CREATE INDEX idx_invitation_email ON invitation (email)');
        $this->addSql('CREATE UNIQUE INDEX uniq_invitation_token ON invitation (token)');
        $this->addSql('CREATE TABLE price_snapshot (id UUID NOT NULL, date DATE NOT NULL, close NUMERIC(20, 8) NOT NULL, currency VARCHAR(3) NOT NULL, source VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, instrument_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4EFB2E22CF11D9C ON price_snapshot (instrument_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_price_instrument_date ON price_snapshot (instrument_id, date)');
        $this->addSql('CREATE TABLE refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE transaction (id UUID NOT NULL, broker_type VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, trade_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, quantity NUMERIC(24, 8) NOT NULL, price_per_share NUMERIC(20, 8) NOT NULL, currency VARCHAR(3) NOT NULL, fee NUMERIC(20, 4) DEFAULT \'0\' NOT NULL, fee_currency VARCHAR(3) NOT NULL, notes TEXT DEFAULT NULL, source VARCHAR(255) NOT NULL, external_id VARCHAR(128) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id UUID NOT NULL, instrument_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_723705D19B6B5FBA ON transaction (account_id)');
        $this->addSql('CREATE INDEX IDX_723705D1CF11D9C ON transaction (instrument_id)');
        $this->addSql('CREATE INDEX idx_tx_account_instrument ON transaction (account_id, instrument_id)');
        $this->addSql('CREATE INDEX idx_tx_account_date ON transaction (account_id, trade_date)');
        $this->addSql('CREATE UNIQUE INDEX uniq_tx_external ON transaction (account_id, broker_type, external_id)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, name VARCHAR(120) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON "user" (email)');
        $this->addSql('ALTER TABLE account_membership ADD CONSTRAINT FK_7A6420219B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE account_membership ADD CONSTRAINT FK_7A642021A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE broker_connection ADD CONSTRAINT FK_1935D6609B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE import_batch ADD CONSTRAINT FK_155EFD1A9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A29B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A2A7B4A7E3 FOREIGN KEY (invited_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE price_snapshot ADD CONSTRAINT FK_4EFB2E22CF11D9C FOREIGN KEY (instrument_id) REFERENCES instrument (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D19B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1CF11D9C FOREIGN KEY (instrument_id) REFERENCES instrument (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE account_membership DROP CONSTRAINT FK_7A6420219B6B5FBA');
        $this->addSql('ALTER TABLE account_membership DROP CONSTRAINT FK_7A642021A76ED395');
        $this->addSql('ALTER TABLE broker_connection DROP CONSTRAINT FK_1935D6609B6B5FBA');
        $this->addSql('ALTER TABLE import_batch DROP CONSTRAINT FK_155EFD1A9B6B5FBA');
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT FK_F11D61A29B6B5FBA');
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT FK_F11D61A2A7B4A7E3');
        $this->addSql('ALTER TABLE price_snapshot DROP CONSTRAINT FK_4EFB2E22CF11D9C');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D19B6B5FBA');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1CF11D9C');
        $this->addSql('DROP TABLE account');
        $this->addSql('DROP TABLE account_membership');
        $this->addSql('DROP TABLE broker_connection');
        $this->addSql('DROP TABLE import_batch');
        $this->addSql('DROP TABLE instrument');
        $this->addSql('DROP TABLE invitation');
        $this->addSql('DROP TABLE price_snapshot');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE "user"');
    }
}
